function hPupilData = preprocessMatBatch(matFolder, opts)
arguments
	matFolder string {mustBeFolder}
	opts.customSettings = [];
    opts.export logical = true
end
% CHANGED THE ARGUMENT HANDLING
customSettings = opts.customSettings;
if isempty(customSettings)
    % Get settings the standard setttings:
    customSettings  = PupilDataModel.getDefaultSettings();
    
    
    % Customize settings (the current dataset features arbitrary units; as
    % such, no absolute maximum can be applied. Instead, the max is set to
    % infinite, and the min to a really low values):
    customSettings.raw.PupilDiameter_Max = 9;
    customSettings.raw.PupilDiameter_Min = 1.5;
    
    % exclude pupil data based on tracking gaze out of screen limits (removes some artifacts?)
    customSettings.raw.exclude_gazebased = false;
    
    
    % The following flag determines if the raw data filter saves information
    % about each intermediate filter step. Enabling it uses considerably more
    % memory, and makes plotting multiple files slow. Use it only when
    % designing and tweaking the filter parameters.
    customSettings.raw.keepFilterData    = true;
    
    %We increase the max gap lengths we interpolate from 250ms (default)
    customSettings.valid.interp_maxGap   = 400;
    customSettings.valid.interp_upsamplingFreq = 500;
end


% Construct one PupilDataModel instance per file using the bacthConstructor
matfiles = dir(fullfile(matFolder, "*.mat"));
if isempty(matfiles)
    error("no .mat files found")
end
nFiles           = length(matfiles);

% Display file information:
printToConsole('L1');
printToConsole(1, 'Found %i files...\n', nFiles);
printToConsole(2, 'Starting analysis pipeline');
printToConsole('L2');

hPupilData = PupilDataModel.batchConstructor(...
    [char(matFolder) '/'],matfiles,customSettings);


%% Filtering the Raw Data:
% Raw raw data contain samples that are either 'valid' or 'invalid'; the
% latter being the result of a measurement artifact or a physical
% disturbance, such as a blink. These invalid datapoints do not contain
% information that we want to carry into our interpolated smooth signal,
% and therefore need to be filtered out. This is done by the filterRawData
% method, which, through the steps described in the accompanying article,
% marks a subset of the raw samples as being 'valid'.


% ADDED: removed bad eye based on standard deviation threshold
threshold = 4;
hPupilData = purge_bad_eye(hPupilData,threshold);

% Run standard pipeline:
hPupilData.filterRawData();


%% Interpolating and Filtering the Valid Samples:
% Once the valid samples are identified, they can be used to create a
% smooth high-resolution pupil size signal through interpolation and
% low-pass filtering, which is what the processValidSamples method does.

% Process the valid samples:
hPupilData.processValidSamples();


%% Analyze Processed Data:
% After processing the valid samples, the pupil size data must be analyzed
% per segment. These segments are defined in the hPupilData instance, see
% the RawFileModel documentationn for details. The analyzeSegments method
% analyzes either the sole available pupil, or both pupils and their mean,
% and horizontally concatenates the results, together with the segmentsData
% table, per PupilDataModel instance. The results are returned in a cell
% array.

% Get the analysis results, vertically concatenate them, and view the
% resulting master table:
results      = hPupilData.analyzeSegments();
try
    PupilResults = vertcat(results{:});
catch
%     warning('Unable to vertically concatenate tables due to different number of variables.');
    PupilResults = results{1}(:,[4 1 2 3 5:end]);
    for pr = 2:size(results,1)
        PupilResults = outerjoin(PupilResults,results{2}(:,[4 1 2 3 5:end]),'MergeKeys', true);
    end
end

% save data

if opts.export
    postMatFolder = regexprep(matFolder, "(\w*)($|(?:\\|/)*$)","$1-processed");
    mkdir(postMatFolder);
    for h = 1:length(hPupilData)
        thisData = hPupilData(h);
        save(fullfile(postMatFolder, thisData.filename), "thisData");
    end
end
% All pupil size data are now saved in the results table. If baseline
% correction is desired, the baseline segments can easily be subtracted
% from their concerning response epoch(s). To simplify this, it is handy to
% add a metadata column to the segmentData table containing an identifier
% labeling the epoch as a baseline. A baseline table can then be generated
% by extracting the rows featuring the baseline identifier from the results
% table. Similarly, a response table can be generated by extracting the
% desired response epochs. These baseline and response tables can then be
% combined using the 'join' table operation, producing a table with
% matched baseline and response columns.


%% Visualizing the Data:
% The PupilDataModel class can visualize its data via the plotData method,
% which can be called on a PupilDataModel array. Note that if the
% keepFilterData flag was set to true, the intermediate filering steps will
% be plotted as well, which may be slow when plotting multiple objects.
%
% The segments are visualized as stacked non-overlapping rectangles in the
% top axes. Their colors are random. 
%
% *** You can click the segment rectangle to view its info ***.

% Plotting:
%hPupilData.plotData;



