function T_export = fET_InitialiseStatsTable(sessions)

% sessions = cellstr(sessions);
T_export = table(sessions,'VariableNames',{'session'});
newColsExp = {'Ntr_Tot'	'Ntr_Test' 'Ntr_OptIn'	'Ntr_OptOut' ...
    'Ntr_Easy' 'Ntr_Medium' 'Ntr_Hard' 'Ntr_xHard' 'Ntr_Harder' ...
     'Ntr_Corr' 'Ntr_Incorr' ...
    'accuracy' 'accuracyEasy' 'accuracyHarder' 'accuracyHvsE' 'accuracyPriorCorr' 'accuracyPriorIncorr' 'accuracyPIvsPC' ...
    'nFixExpB' ...
    'nFixExpB_PriorCorr' 'nFixExpB_PriorIncorr' 'nFixExpB_PIvsPC' ...
    'nSwitchExpB' ...
    'nSwitchExpB_PriorCorr' 'nSwitchExpB_PriorIncorr' 'nSwitchExpB_PIvsPC' ...
    'decLat' ...
    'decLat_PriorCorr' 'decLat_PriorIncorr' 'decLat_PIvsPC'};
for iLoop = 1:length(newColsExp)
    T_export.(newColsExp{iLoop}) = NaN(height(T_export), 1);
end

end